name: EarthFast Release

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Build application
        run: |
          npm install
          npm run build

      - name: Bundle release for EarthFast
        uses: ./earthfast-release-action
        id: earthfast
        with:
          build_dir: out
          bundle_name: sid-test-${{ github.ref_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Log the EarthFast bundle data
        run: |
          echo "EarthFast bundle url: ${{ steps.earthfast.outputs.bundle_url }}"
          echo "EarthFast bundle checksum: ${{ steps.earthfast.outputs.checksum }}" 